name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or whichever branch you want to build from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build the Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/linkwarden:latest .

      - name: Push the Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/linkwarden:latest
