name: Sync Upstream

on:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 02:00 UTC, which is 5:00 AM GMT+3
  workflow_dispatch:     # Allows manual triggering from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork's main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/linkwarden/linkwarden.git || echo "Upstream remote already exists"

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git merge upstream/main --no-edit || echo "No changes to merge"

      - name: Push Changes
        run: git push origin main
